Error
    at Context.<anonymous> (/Does/Not/Exist/test/raven.client.js:43:36)
    at Test.run (/Does/Not/Exist/node_modules/mocha/lib/runnable.js:143:15)
    at Runner.runTest (/Does/Not/Exist/node_modules/mocha/lib/runner.js:272:10)
    at /Does/Not/Exist/node_modules/mocha/lib/runner.js:316:12
    at next (/Does/Not/Exist/node_modules/mocha/lib/runner.js:199:14)
    at /Does/Not/Exist/node_modules/mocha/lib/runner.js:208:7
    at next (/Does/Not/Exist/node_modules/mocha/lib/runner.js:157:23)
    at Array.0 (/Does/Not/Exist/node_modules/mocha/lib/runner.js:176:5)
    at EventEmitter._tickCallback (node.js:192:40)